### ISSUE TITLE
[JSX] using html attributes

### ISSUE THREAD

**Issue by youzi** [vigour-io/builder-boy#73]
In React land adding html attributes in jsx is the same as in html (http://magic.reactjs.net/htmltojsx.htm) in Brisky-render we need to add the property 'attr'.

this looks like this, eg:
```jsx
<input attr={{ type: 'range' }} />
```
vs
```jsx
<input type='range' />
```

We should support the latter => we can add this in either builder-boy or brisky-render itself. 

/cc @jimdebeer

**Comment by jimdebeer** [comment]
works for everything except type -- need to change in render
